In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [18]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [5]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
a = np.array([1, 2, 3])
b = np.zeros(5)
c = np.ones((3, 4))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

In [9]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3,)
1
3
int64


#Indexing and slicing

In [13]:
arr=np.array([10,20,30,40,50])

print(arr[0])
print(arr[2:4])                           # :=Slicing within array   and  # ,= rows and column


print("---------------------------------------------")
# Boolean Indexing

arr = np.array([1, 5, 10, 15, 20])
print(arr[arr > 10])

10
[30 40]
---------------------------------------------
[15 20]


In [15]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])

print(arr1+arr2)
print(arr1*arr2)

[50 70 90]
[ 400 1000 1800]


In [16]:
x = np.array([1, 2, 3])

print(x + 5)  # Broadcasting: adds 5 to each element

print(np.sqrt(x))
print(np.exp(x))
print(np.log(x))

print(np.mean(x))
print(np.median(x))
print(np.std(x))
print(np.sum(x))

[6 7 8]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
2.0
2.0
0.816496580927726
6


Reshaping

In [17]:
m = np.arange(12)
print(m)
m2 = m.reshape(3, 4)
print(m2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### ML Numpy 

### 1.scalling

In [19]:
X= np.array([[1,2,3],
             [4,5,6]])
mean = np.mean(X, axis=0)  # Mean of each column
#maen1=X.mean(axis=0)  # Mean of each column
                                                    # axis=1 :row wise 
                                                    # axis=0 :column wise
mean2=X.mean(axis=1)  # Mean of each row

X_centered= X-mean # Broadcasting  and makeing the mean zero(scalling)

print(mean)
print(X_centered)

[2.5 3.5 4.5]
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


### vectorization

In [21]:
result = X * 2    # scalling by a factor of 2 , using broadcasting
                 # instead of looping through each element
print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [23]:
np.random.rand(5, 3)  # 5 samples, 3 features

array([[0.05452382, 0.20455483, 0.3700991 ],
       [0.97686544, 0.06201114, 0.60242216],
       [0.34967251, 0.835547  , 0.34370115],
       [0.92962889, 0.05020832, 0.9508622 ],
       [0.55078259, 0.85845834, 0.91994074]])

In [24]:
col_mean = X.mean(axis=0)  # per feature
row_mean = X.mean(axis=1)  # per sample

print(col_mean.shape)  # (3,)
print(row_mean.shape)  # (5,)

(3,)
(5,)


### 3. Condition and masking

In [27]:
X = np.array([0.2, 0.6, 0.9, 0.1])

X[X < 0.5] = 0
print(X)

# or 

X_new = np.where(X > 0.5, 1, 0)       #np.where(condition, a, b)
print(X_new)

[0.  0.6 0.9 0. ]
[0 1 1 0]


In [28]:
arr = np.array([10, 20, 30, 40, 50])

idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


### 4. Stacking and concatenation

In [35]:
A = np.ones((3, 2))
B = np.zeros((3, 2))

h = np.hstack([A, B])   # add features                
v = np.vstack([A, B])   # add samples

                         #all the input array dimensions except for the concatenation axis must match exactly
print(h)
print("----------------------------------------------")
print(v)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
----------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### 5. Linear Algebra

In [38]:
X = np.random.rand(100, 3)
w = np.random.rand(3, 1)

y_pred = X @ w   # matrix multiplication
print(y_pred.shape)

(100, 1)


In [ ]:
np.dot(X, w)
np.linalg.inv(A)               #Computes the exact inverse of a square, non-singular matrix

np.linalg.pinv(A)          # computes pseudo-inverse (works even if matrix is not invertible)

np.linalg.norm(x)         # Computes the magnitude (length) of a vector or matrix

### 6. Randomness

In [54]:
np.random.seed(100)        # change seed value to get different random numbers

X = np.random.randn(100, 5)
print(X[:5])  # first 5 samples

[[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]
 [ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]
 [-0.45802699  0.43516349 -0.58359505  0.81684707  0.67272081]
 [-0.10441114 -0.53128038  1.02973269 -0.43813562 -1.11831825]
 [ 1.61898166  1.54160517 -0.25187914 -0.84243574  0.18451869]]


### 7. View vs copy

In [57]:
a = np.arange(10)
b = a[2:5]   # view
b[:] = 99
print(a)    # original changes

#force copy
c = a[2:5].copy()
c[:] = 55
print(a)    # original unchanged

[ 0  1 99 99 99  5  6  7  8  9]
[ 0  1 99 99 99  5  6  7  8  9]


# MINI ML 


In [58]:
#1.Feature Normalization
X = np.random.rand(100, 3)

m = X.mean(axis=0)      #feature
print("mean",m)
sigma = X.std(axis=0)
print("std",sigma)

X_norm = (X - m)/ sigma

mean [0.53539069 0.44519106 0.53071302]
std [0.28594438 0.25305113 0.27287043]


In [ ]:
#Linear regression prediction
def predict(X, w, b):
    return X @ w + b

In [ ]:
#Mini batch Sampling
def get_minibatch(X, y, batch_size=32):
    idx = np.random.choice(len(X), batch_size, replace=False)
    return X[idx], y[idx]

# Notes


### 1. Array Creation

    np.array() — create array from list

    np.zeros(shape) — array of zeros

    np.ones(shape) — array of ones

    np.arange(start, stop, step) — range values

    np.linspace(start, stop, num) — evenly spaced values

    np.random.rand() — uniform random
    
    np.random.randn() — normal distribution



### 2. Array Properties

    arr.shape — dimensions

    arr.ndim — number of dimensions

    arr.size — total elements

    arr.dtype — data type


### 3. Indexing & Slicing

    arr[i] — element access

    arr[start:stop] — slicing

    arr[:, j] — column selection
    
    arr[i, :] — row selection

### 4. Broadcasting  
-->Operations between different shapes


### 5. Vectorization (Avoid Loops)

Use array ops instead of Python loops

Faster and cleaner



### 6. Axis Concept (CRITICAL)

axis=0 → column-wise (features)

axis=1 → row-wise (samples)

### 7. Boolean Masking   
\Used for:

Thresholding

Filtering

Label creation


### 8. Fancy Indexing

Used for: Sampling and Mini-batches

### 9. Reshaping

arr.reshape(r, c)

arr.flatten()

arr.ravel()


### 10. Stacking & Concatenation

np.hstack() — add features

np.vstack() — add samples

np.concatenate()

### 11. Mathematical Functions

np.sum()

np.mean()

np.std()

np.min(), np.max()

np.sqrt()

np.exp()

np.log()



### 12. Linear Algebra (ML CORE)

@ or np.dot() — matrix multiply

np.linalg.inv() — inverse

np.linalg.pinv() — pseudo-inverse

np.linalg.norm() — vector/matrix norm

np.linalg.eig() — eigenvalues (PCA)



### 14. Views vs Copies

Slicing → view (changes original)

.copy() → independent copy